theme = "tokyonight_storm"

[editor]
line-number = "relative"
mouse = true
auto-completion = true
true-color = true
auto-info = true
completion-trigger-len = 1
#gutters = ["diagnostics", "line-numbers"]
scroll-lines = 3
shell = ["sh", "-c"]
middle-click-paste = true

[editor.cursor-shape]
insert= "bar"
normal= "block"
select= "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.search]
smart-case = true
wrap-around = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[keys.normal]
#